apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monolith2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: monolith2
    spec:
      containers:
      - name: monolith2-app
        image: teja59/monolith2
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        ports:
        - containerPort: 8080
